menu:
  - id: "add_formula_node"
    label: "Добавить формулу"
    # icon: "Formula"
    action: "addNode"
    nodeType: "formulaNode"
  - id: "add_python_node"
    label: "Добавить Python-скрипт"
    # icon: "Code"
    action: "addNode"
    nodeType: "pythonNode"
  - separator: true
  - id: "paste_node"
    label: "Вставить узел"
    # icon: "Paste"
    action: "pasteNode"
    # enabledIf: "clipboardHasNode"