menu:
  - id: "delete_node"
    label: "Удалить узел"
    # icon: "Delete"
    action: "deleteNode"
  - separator: true
  - id: "add_after_formula"
    label: "Добавить формулу после"
    # icon: "Add"
    action: "addNodeAfter"
    nodeType: "formulaNode"
  - id: "add_after_python"
    label: "Добавить Python-скрипт после"
    # icon: "Add"
    action: "addNodeAfter"
    nodeType: "pythonNode"
  - separator: true
  - id: "duplicate_node"
    label: "Дублировать"
    # icon: "Copy"
    action: "duplicateNode"