menu:
  - label: "Файл"
    items:
      - id: "new_project"
        label: "Новый проект"
        # shortcut: "Ctrl+N"
        # icon: "DocumentAdd"
      - id: "open_project"
        label: "Открыть проект"
        # shortcut: "Ctrl+O"
        # icon: "FolderOpen"
      - separator: true
      - id: "export_xlsx"
        label: "Экспорт в XLSX"
        # shortcut: "Ctrl+E"
        # icon: "Export"
  - label: "Главная"
    items:
      - id: "bold"
        label: "Жирный"
        # shortcut: "Ctrl+B"
        # icon: "Bold"
        group: "font"
      - id: "italic"
        label: "Курсив"
        # shortcut: "Ctrl+I"
        # icon: "Italic"
        group: "font"